### ISSUE TITLE
表記ガイドラインの見直し 2018

### ISSUE THREAD

**Issue by marsf** [mozilla-japan/translation#260]
[表記ガイドライン](https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline) を年に 1 回くらい見直して更新していきたいです。
この issue にコメントください。

[日本語の文体](https://docs.google.com/spreadsheets/d/1y-hC-xMXawCgcYZwJDnvuSlAOTgMRLLyqXurpYkJbYE/edit#gid=0) についてのコメントも歓迎。

とりあえずコメント受付は8月末まで。コメントの内容を検討して、ガイドライン更新を年末までにという感じでいかがでしょうか。

**Comment by c-bou-kojima** [comment]
とりあえず、揺れやすい表記を集めてみます。

**Comment by Uemmra3** [comment]
-「とき」「ところ」「もの」「こと」
--    特定の時刻や場所を表す場合は「時」「所」

**Comment by momdo** [comment]
「日本語の文体」ですが、法則性が見えないのが現時点でつらいかなという感想です。

**Comment by c-bou386** [comment]
Uemmra3さん：
ご指摘、もっともです。これらの言葉には、意味が複数存在することが一因かと思います。同様に、
「まえ」「あと」「なか」
も難しいです。時刻、位置、概念的なことも含みます。たとえば「なかには、こんな表現もある」といった場合、「なか」は、in・outではないですよね。だから「中」は使いたくないです。
では、こういった問題をどう対応すべきか？　ひとつ提案したのは、「悩んだらひらがな」です。この20年くらいの流れ的には、漢字を使わない傾向が強いです。
で、もっとも重要なのが、2つ。同じドキュメントで「全て」や「すべて」が混在するような状態は、好ましくない…　この判断、よろしいでしょうか？　実は最近、ちょっと異なる出版文化で仕事を始めましたが、そういうことをまったく無視する世界もありました。すごくキモイですけどね。
あとは、これから翻訳などをしてくださる方にわかりやすいガイドラインを提示できるかがもっとも重要かと思います。
出版社などで、30年くらい編集者をしてきました。この手の問題に関して、不毛な議論も多々経験してきました。どれが正解ではないです。MDNのドキュメントをどうそろえていくか。そのベース作業かと思います。よろしくお願いします。

**Comment by c-bou386** [comment]
[揺れやすい用語.zip](https://github.com/mozilla-japan/translation/files/1755788/default.zip)
揺れやすい用語をまとめてみました。1990年頃からの蓄積です。IME（当時はFEP）では、出ないような言葉もありますね。「必らず」なんて、過去ですね。その頃ですので、手書き原稿も想定していました。2002年くらいまで、文部省に逆らって。「行なう」「表わす」を使っていました。まずは、上の項目を漢字にするか、かなにするかを決めていくのでもいいかと思います。
繰り返しますが、どちらが正解というのが難しいのもあります。また、前後の関係で変わってくるのもあるでしょう。好みもあるでしょう。繰り返しになりますが、最近では、かなのほうが多くなっていますね。「作る」なんて新聞ではほとんどないです。私の方向としては、今後を踏まえれば、開きを多くしていったほうがよいかと思います。

**Comment by Uemmra3** [comment]
@c-bou386 プロの編集者の方だったんですね。心強いです！

> では、こういった問題をどう対応すべきか？　ひとつ提案したのは、「悩んだらひらがな」です。この20年くらいの流れ的には、漢字を使わない傾向が強いです。

なるほど、ある程度の傾向があるのですね。

[表記ガイドライン](https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline) の適用範囲については、一応 MDN(開発者用の文書)だけでなく、marsf さんがミートアップ時に呼びかけられてた SUMO(サポートサイト)や、製品版(Firefox や Thunderbird自体)にもかかってくるものだと思います。

**Comment by momdo** [comment]
>表記ガイドライン の適用範囲については、一応 MDN(開発者用の文書)だけでなく、marsf さんがミートアップ時に呼びかけられてた SUMO(サポートサイト)や、製品版(Firefox や Thunderbird自体)にもかかってくるものだと思います。

そういえば、表記ガイドラインを適用する範囲が表記ガイドライン自体に記述されていないですね…。これは問題があるのでは。また、強制力があるのか、あくまで目安なのかといったところも気になります（とはいえMDNでなにがしかを強制するのは難しいと思いますが。）

**Comment by Uemmra3** [comment]
こと MDN に関しては、更新の速い開発者用の文書をボランティアベースで更新しているということもあって、現状は貢献者リソースを増やして翻訳済みページ/更新済みページの割合を上げるのが優先度高いかなと思っています(そういう意味でミートアップの意義は大きい)。

もちろん質的な問題をおざなりにしていいわけではなくて、ある程度の方向づけをしていかないといけないですが、momdo さんの指摘にもあるように

> 「日本語の文体」ですが、法則性が見えないのが現時点でつらいかなという感想です。

ガイドラインが敷居に感じられても困るので貢献者にとって利用しやすいものにしたいですね。

あとはこれまでは翻訳者≒編集者だったのですが、分業体制にするとか、ガイドラインのチェックツールなどがあったらいいのかもしれません。

**Comment by momdo** [comment]
Uemmra3さんのおっしゃってることには概ね同意で、いろいろと周辺課題はあると思いますがそれはさておき。

>> 「日本語の文体」ですが、法則性が見えないのが現時点でつらいかなという感想です。

> ガイドラインが敷居に感じられても困るので貢献者にとって利用しやすいものにしたいですね。

たとえば、長音のありなしだと英語の綴りに応じてこうする、というのが現在の表記ガイドラインではある程度見えるわけで、これに類するような何かの法則性（例えば日本語の品詞）なんかがあると、まだ見通しが良くなるのかな、という印象です（c-bou386さんが整理していただいたものも同様に）。

ただ、Uemmra3がコメントされているように、ガイドラインのチェックツールがもしあれば、そういった法則性をあまり気にしなくてもよいのかもしれません。

**Comment by marsf** [comment]
c-bou386 さん:
揺れやすい用語の表、すばらしいです。共有していただいてありがとうございます。

momdo さん:
日本語の文体のリストは、いまのところ完全に記者ハンドブックからの抜粋です。
法則性が見られないのは、ハンドブックに法則性が見られないということです :-p
momdo さんのおっしゃる通り、法則性が見えるようにしたいですね。

**Comment by Uemmra3** [comment]
ping

**Comment by hmatrjp** [comment]
（他の方からコメント付くかなと思っていたのですが、まだなさそうなので）
私が（オンラインも含めて）2回参加した中では、特にありませんでした。

**Comment by marsf** [comment]
共同通信の記者ハンドブック 第13版で @c-bou386 さんの「揺れやすい用語」リストの単語を確認したいけど、まだそこまで手が回らない。品詞も含めて分類しないとな。

**Comment by marsf** [comment]
それから、-cy [-si] (ポリシー、プライバシー) は長音付けてるので、-xy [-ksi] (プロキシー) も長音にしたいです。

**Comment by marsf** [comment]
@momdo さん
> そういえば、表記ガイドラインを適用する範囲が表記ガイドライン自体に記述されていないですね…。これは問題があるのでは。また、強制力があるのか、あくまで目安なのかといったところも気になります（とはいえMDNでなにがしかを強制するのは難しいと思いますが。）

遅レスですみません。
このガイドライン適用が強制されるのは、少なくとも製品のローカライズと公式サイトです。公式サイトは、具体的には現在 [Pontoon でローカライズされているサイト](https://pontoon.mozilla.org/ja/)等を指します。

それ以外の翻訳記事などは、製品やサイトの表記に従っていただくというのが基本です。もちろんそれらへの強制力はありませんが、ガイドラインとして活用していただけると、Mozilla 関連文書の統一が取れるし、文書の品質を上げる助けになります。

**Comment by marsf** [comment]
追記：これは個人の意見ではなく、製品および公式サイトのローカライズをしているメンバーの共通認識です。
（違ってたらツッコミよろしく）

**Comment by marsf** [comment]
8月末を過ぎたので、検討事項をまとめるため一旦締め切ります。
(が、何か思いついたことなどあれば、ご自由にコメントを残してください。今後の参考にします。)

**Comment by marsf** [comment]
見直しの要望まとめ：
- [ ] (1)「日本語の文体」の漢字とひらがなの使い分け、法則性が見えない。([Uemmra3 さん](https://github.com/mozilla-japan/translation/issues/260#issuecomment-367552870)、[momdo さん](https://github.com/mozilla-japan/translation/issues/260#issuecomment-367560075)、[c-bou386 さん](https://github.com/mozilla-japan/translation/issues/260#issuecomment-368224237))
- [ ] (2) 表記ガイドラインを適用する範囲が表記ガイドライン自体に記述されていない。([momdo さん](https://github.com/mozilla-japan/translation/issues/260#issuecomment-368290450))
- [ ] (3) -xy [-ksi] (プロキシー) も長音をつけたい。([marsf](https://github.com/mozilla-japan/translation/issues/260#issuecomment-411083753))

※名前部分は、このページ内の各コメントへのリンクです。

**Comment by marsf** [comment]
(1) について、
「[日本語の文体](https://docs.google.com/spreadsheets/d/1y-hC-xMXawCgcYZwJDnvuSlAOTgMRLLyqXurpYkJbYE/edit#gid=0)」に 2018 (draft) のシートを追加しました。
- 記者ハンドブック第13版に準拠。
- c-bou さんの「揺れやすい用語リスト」から、ガイドラインに必要そうなものを独断と偏見で抜き出してリスト後半に追加。
- 各用語の品詞も追加。

何か、漢字とひらがなの使い分けの法則性が見えないかと、手元のデータでは副詞をさらに分類してみているのですが未完成なので載せていません。副詞の研究中。

**Comment by marsf** [comment]
(2) について、
特に異論がなければ、[8/8 コメント](https://github.com/mozilla-japan/translation/issues/260#issuecomment-411417486)の
>  このガイドライン適用が強制されるのは、少なくとも製品のローカライズと公式サイトです。公式サイトは、具体的には現在 Pontoon でローカライズされているサイト等を指します。

を手直ししてガイドラインに追加する、ということでよろしいでしょうか。

**Comment by marsf** [comment]
(3) はご意見募集。ご検討お願いします。

**Comment by marsf** [comment]
それから、@Uemmra3 さんが [TranslationHelper](https://github.com/mozilla-japan/translation/tree/master/MDN) を改良してくださっています。ありがとうございます。

**Comment by hmatrjp** [comment]
(1)
> 何か、漢字とひらがなの使い分けの法則性が見えないかと、手元のデータでは副詞をさらに特性で分類してみているのですが未完成なので載せていません。副詞の研究中。

一覧を眺めてみたところ、ひらがなと漢字と、どちらのトータル画数が少ないか、で決めているように見えます。（それだけ、ではなさそうですが。）


(3)
Proxy プロクシー　賛成です。
他に -xy で終わるものありましたかね？

**Comment by c-bou386** [comment]
すみません。自分で提案をしておきながら、放置状態でした。実は、仕事で外部校正（たんに外校とも）をしております（今日も江戸川橋近辺で）。仕事は、誤字脱字の指摘、用語統一といったことが多いです。素読みをしながら問題個所を指摘していきます。仕事開始時に、用語表や●×記者ハンドブックを渡されることもあり、これに従えと…　しかし、ほとんどがめちゃくちゃですね。今日も多々指摘しました。で、あまり多く指摘すると、「こんなに赤字入れやがって」と嫌な顔をされることも少なくありません。ひどい世界です。つまり、商業レベルでも用語統一がほぼ完全に行われていることは少ないです。
そして、もっとも重要なのが、論理的、文法的、理性的に統一を行うのは不可能な点です（これは、いくつかの例を後述します）。最低限、その記事、そしてページ、本（ウェブではサイト全体）で不統一が極力少ない方がよいということです。それは、妥協による合意だと思います。
まず指摘したいのは、読み方での統一です。以下のサンプルをみてください。
--
といった例などを見ればわかるだろう。別な事例として、他言語等がある。そのほかにもいくつか紹介したい。
--
さて、ここでは「等」と「他」ですね。「など」「ほか」と読む場合は開き、「とう」「た」と読む場合は閉じる…　では「他言語等」はどう読みますか？　「たげんごなど」「たげんごとう」どちらでも読めると思います。つまり、読み方で使い分けるのは不統一の原因になりやすいです。私は編集者時代、こういった場合は、「ほかの言語など」と文章自体を変更し、なるべく読み方に違いが生じない処理をしていました。
文法的に統一。たとえば、動詞は閉じ、それ以外は開くというルールです。しかし、「ある」と「ない」ではどうなるか。「ある」は動詞なので「有る」、「ない」は形容詞なので「ない」で「無い」はNG…　納得できるでしょうか。そもそも、あるが動詞で、ないが形容詞や助動詞という文法自体がまちがっているような気がします（大学時代の文学の先生の教え。日本語に助動詞がありえない。あくまで考え方の1つですが…）。
最後に、それを決めたことで、ほかへの影響が発生してしまう例です。これは、Mozilla L10n-jaで「時に」が漢字となっています。「時」は、いろいろな使われかたがあります。

・文頭で「時には、このような…」
・漢字の後ろについて「発生時に」
・「●×する時に」

組み合わせやこれも上の読み方などと絡むことがあり、揺れやすいです。それと「組合せ」などに見られる送りの違いですね。たとえば、

・申し込み
・申込み
・申込

どう使い分けるか。先々週、銀行のマニュアルで「●×にお申し込みいただくには、先に△▽会員に申込みください」って何？　これだけで20か所以上あり。指摘された編集さんが頭かかえていました(^^;)。金曜日の仕事で、納期が翌週の月曜日とか…

以下は、私の感想ですが、最近は開くことが多いです。新聞などでは「つくる」はほとんどが開いています。傾向として、どちらかに悩んだら、開くという方針もありかと思います。また、ここで、すべてを決定することもなく、適宜、見直しもありかと思います。私のようなフルに翻訳ができない人間は、用語統一の作業だけでも多々あるかと思います。重要な文書から、順次、修正していけばいいと思います。参考になれば幸いです。

**Comment by c-bou386** [comment]
なぜ、フォントサイズが…　わからん。

**Comment by Uemmra3** [comment]
とりあえず[残課題](https://github.com/mozilla-japan/translation/issues/260#issuecomment-427559849)について

(1)については、なかなか難しいですね。
個人的には「ひらがな多用だと小学生っぽくてイマイチかな？」と思っていたのですが、
@c-bou386 さんの商業誌編集経験からすると「開く」方が、多くの人に理解しやすくていいのかな？
と思うようになりました。

(2)については、8/8のコメントベースで良いかとー。

(3)も長音化で問題ないと思います。
ほかには Firefoxy とかあるけど、それはFirefoxらしさか。。

**Comment by Uemmra3** [comment]
@c-bou386 フォントサイズの件は、GitHubのマークダウンというドキュメント記法の仕様だと思います。
参照: [Markdown記法チートシート](https://gist.github.com/mignonstyle/083c9e1651d7734f84c99b8cf49d57fa)

bold text
---
hogehoge

normal text

---
fugafuga

**Comment by c-bou386** [comment]
T. Uemura　さま：
しょうもないこと長々とすみません。一言でいえば、
・現時点で、完璧を求める必要はない
だと思います。また、気になれば「これは開いたほうがよくない？」とか、「やっぱ漢字だよね」で、相談すればよいかと思います。とりあえず、この後の成案を拝見したく。
それと、Marさんには申し訳ないですが、両論併記がもっとも混乱の原因です。今回の例でいえば、「既に」ですね。難しくても、どちらかを選択すべきです。これから翻訳する人には、その使い分けなんて意識できないです。
フォントの件もありがとうございました。SNSを含め、こういったツールはほとんど使ってない人間なので、完全初心者です。また、お手を煩わせるかと思いますが…　先に誤っておきます。すみませんm(..)m

**Comment by marsf** [comment]
メモ：

- [語種 - Wikipedia](https://ja.wikipedia.org/wiki/%E8%AA%9E%E7%A8%AE)
- [動詞・副詞・形容語の「和語対非和語語種比率」（ＲＪＦ）による現代日本語文体の計量的比較考察](https://glim-re.repo.nii.ac.jp/?action=pages_view_main&active_action=repository_view_main_item_detail&item_id=3292&item_no=1&page_id=13&block_id=21)
和語語種率（RJF）（％)＝和語語数÷（動詞・形容語・副詞の総数）×100
やわらかい文体、硬い文体

**Comment by marsf** [comment]
気が付いたら年末になってました。
(2), (3) は特に異論がないようなので、そのままガイドラインに反映させます。

(1) についての論点：
- 「とき」「ところ」「まえ」「あと」「なか」の表記。ひらがな表記にする（開く）か、漢字表記にする（閉じる）かの判断。
- 論理的、文法的、理性的に統一を行うのは不可能。読み方で統一する方法がある。または文法（品詞）的に統一する方法もあるが揺れやすい。（「ある」「ない」の表記）
- 漢字とひらがなの表記が混在しないほうがよい。両論併記は混乱の原因になる。
- 送り仮名の使い分け。

**Comment by marsf** [comment]
> 論理的、文法的、理性的に統一を行うのは不可能。読み方で統一する方法がある。文法（品詞）的に統一する方法は揺れやすい。（「ある」「ない」の表記）

文法的に言えば、「ある」の表記には、存在概念を表すもの（動詞）と、「～である」のように判断・陳述を表すもの（いわゆる助動詞）の区別があります。「ない」も同様に、概念を表すもの（形容詞）と判断・陳述を表すもの（いわゆる助動詞）の区別があります。
「いわゆる助動詞」それ自体は、具体的か抽象的かとは無関係ですから、そもそも文法の理解に誤りがあります。理解に誤りがあるので、矛盾が生じて統一できないのです。


※「いわゆる」と書いたのは、学校教育で教えている助動詞ではなく、[補助動詞](https://ja.wikipedia.org/wiki/%E5%8A%A9%E5%8B%95%E8%A9%9E_(%E5%9B%BD%E6%96%87%E6%B3%95))のこと。

**Comment by marsf** [comment]
> 送り仮名の使い分け。

ガイドラインでは、「動詞の送りがなは本則に従う。○ 読み込み、貼り付け × 読込み、貼付け」としています。

**Comment by marsf** [comment]
漢字表記の場合は、意味が定まり、読みが定まらない。
ひらがな表記の場合は、読みが定まり、意味が定まらない。
なので、「読み方で統一する」＝「ひらがな表記にする」となる。

副詞に関して言えば、その副詞の意味は、修飾する語句に依存するものなので、「具体的な事柄は漢字、抽象的な内容はひらがな」という基準は成り立たない。
副詞も、同じ語で程度を示すものと、陳述するものに分けられる。
　　とても：〔程度〕「とてもきれいな景色だ」（とても→きれい）
　　　　　　〔陳述〕「とても自分には信じられない」（とても→ない）

**Comment by c-bou386** [comment]
おおむね、ご提案でよろしいかと思います。送り仮名ですが、業界やドメインで異なることが多いです。金融、株式、流通系などでは、送らないことが多く「申し込み」は「申込」といった表記が多々見受けられます。今回の統一の方向では、考慮する必要はないと思います。
あとは、具体的な統一表（例：https://docs.google.com/spreadsheets/d/1y-hC-xMXawCgcYZwJDnvuSlAOTgMRLLyqXurpYkJbYE/edit#gid=0）を作成し、個々の用語について検討を加えていくのでよろしいかと思います。で、再度ですが、この時点で100％完璧にはならなくてもよい（適宜、修正）の意識も重要かと思います。

**Comment by marsf** [comment]
コメントありがとうございます。
個々の用語を検討するにも、ある程度の判断基準が必要になりますので、以下のようにしてみます。

* 同じ文章内またはカテゴリー内では表記を統一する。
* 「こと」「もの」「とき」「ところ」「まえ」「あと」「なか」
  * ~特定の時刻や場所を表す場合は「時」「所」~
  * 特定の時刻や場所など、具体的な事柄は漢字にする。(_例文を追加する_)

* 接続詞・副詞：
  * ひらがなで表記する。
  * 副詞の「～に」のうち、漢語は漢字でもよい。
  * 文頭を除き、文中の副詞は読みやすさを考慮して漢字でもよい。


以下、削除。
  * ~有り/無し OR あり/なし -- TBD~
  * ~例え (ば) OR たとえ (ば) -- TBD~
  * ~共に OR ともに -- TBD~
  * ~「〜に」は基本的に漢字。例外として「すでに」「さらに」「まれに」「たまに」はひらがなにする。-- TBD~
  * ~「全て」「殆ど」「幾つか」ではなく「すべて」「ほとんど」「いくつか」~
  * ~「但し」ではなく「ただし」~
  * ~「或いは」「又は」「及び」ではなく「あるいは」「または」「および」~

**Comment by marsf** [comment]
ガイドラインに (2) と (3) を反映させました。
お気づきの点があれば、いつでもコメントください。

**Comment by marsf** [comment]
(1) の日本語の文体をガイドラインに反映させました。
https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline#%E6%97%A5%E6%9C%AC%E8%AA%9E%E3%81%AE%E6%96%87%E4%BD%93

**Comment by marsf** [comment]
ガイドラインの文章を整理して、いくつか文言を直しました。
https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline/_compare/d7a054340d1862ca59b94d15176a6def8671dc59...91fb55c6a574a448ffc99b4ca310eee7d257e5bd

このガイドラインは、Mozilla 製品のローカライズと公式サイトに適用されます。～
→ このガイドラインは、Mozilla 製品と公式サイトのローカライズに適用されます。～

全角英数字を用いる例外: 社名など
→ 例外として、社名や商標など登記上の名称には全角英数字を用いる。

カタカナで構成された語句について、～
→ カタカナで構成された複合語については半角スペースを挿入しない。

Firefox の表記に準拠。
→ Firefox で用いている表記に準拠する。

(訳語) ファイアーフォックス
→ (訳語) ファイアフォックス

※Firefox の[商標登録を検索](https://www.j-platpat.inpit.go.jp/)したら、称呼が「ファイアフォックス」「ファイヤフォックス」で登録されてました。(登録4929354)

**Comment by marsf** [comment]
だいぶ時間が経ってしまいました。今回はこれで close します。
